### ISSUE TITLE
Engage more with the community

### ISSUE THREAD

**Issue by al-muammar** [supervisely/supervisely#11]
I would suggest you to engage more with the community. You might outline some low-pri, but pretty important tasks and I'm sure that people would be happy to do them.

The first thing that catches one's eye is the absence of tests and CI. I would be happy to make some changes here and there, but without tests, I'm hesitant to do so, because I might break by it something else.

**Comment by Jihadik** [comment]
I'm not a big fun of jupyter notebooks, but one good thing with them is that you should be able to add integration tests on them. Pretty simple: just run all commands and check that there are no errors. Hence you will prevent desynchronization of your docs and tutorials.

Then wrap it into a CI and prevent merging PRs that break your docs.

**Comment by antonc-ds** [comment]
Hi @Jihadik , thanks for taking the initiative and writing this up! To be honest, I am not sure we have a mature enough internal development process to ask community for contributions towards some of our priorities. My main concern there is that for now we may not be able to provide fast enough turnaround times on PRs and a stable enough base and priorities for external developers, and that would lead to a frustrating experience from the outside.

On the constructive side, what would be actually extremely useful for us is feature requests/proposals and bug reports. Right now we check the error logs on the community instance to see the frequent failure cases that needs to be fixed, but with respect to missing features, it is much more difficult to get feedback. So this is not to say we discourage pull requests, quite the opposite. But unless it is something trivial. before putting in the time, I would start with opening an issue so that we can discuss and align expectations.

Also, some background on the CI and setup overall. The way we have the Python part set up is there is a separate private repo where all the development goes. That repo contains both the public code and some our proprietary components. Once in a while we take the non-proprietary updates from that private repo and publish them here. So not sure for now how to fit a CI setup on the public repo in this model. That private repo actually has a rudimentary CI setup, but as you can see the testing coverage is pretty sad for now. We have a bit of unit tests like here https://github.com/DeepSystems/supervisely_py/blob/master/supervisely_lib/geometry/main_tests.py , but not much. I would start with unit tests first probably, because the integration tests require setting up or mocking out a web instance (and that is rather heavy in terms of complexity).

On the Jupyter notebooks, I am not a fan either for non-interactive tasks, and in fact we have plain Python tasks coming soon that should take over much of the current Jupyter notebooks functionality (like downloading only JSON annotations without images, it does not make much sense to fire up Jupyter for that) and subsume DTL functions too. Some of those scripts are already here: https://github.com/supervisely/supervisely/tree/master/plugins/python/src . We will start by integrating those into the context menus in the web instance, and shortly after plan to enable user-defined scripts to be launched too, which hopefully will reduce the interactions friction for the common tasks.

This turned out to be a long ramble.. Again, we do appreciate you reaching out, and hope that we can find a productive way of collaborating. Any feedback-requests-proposals are very welcome. Thank you!
