### ISSUE TITLE
About agency

### ISSUE THREAD

**Issue by chichu1021** [supervisely/supervisely#1180]
My device is Windows.I read your tutorial.I use the web version of Supervisely.However, the advanced Settings page in the tutorial is different from that in the web, and then I run docker and there will be an error, I don't know what the reason is, and I don't know how to solve it。{"message": "TELEMETRY_REPORTER_INITIALIZED", "service_type": "ServiceType.AGENT", "event_type": "EventType.LOGJ", "worker": "telemetry", "timestamp": "2024-11-17T16:37:36.901Z", "level": "info"}

**Comment by chichu1021** [comment]
{"message": "Temporary connection error, please wait ...", "method": "AgentPing", "url": "https://app.supervisely.com/agent/AgentPing", "details": "HTTPSConnectionPool(host='app.supervisely.com', port=443): Read timed out. (read timeout=4)", "service_type": "ServiceType.AGENT", "event_type": "EventType.LOGJ", "timestamp": "2024-11-17T16:43:43.805Z", "level": "warn"}

**Comment by chichu1021** [comment]
![Uploading bcbaab6d7de11553285e7dbf38a1017.png…]()

**Comment by iwatkot** [comment]
@chichu1021, hello!

We're kindly asking our users to request help and support via our Slack channel: https://supervisely.com/slack/ or e-mail: [support@supervisely.com](mailto:support@supervisely.com)

Sorry for the late reply.

Regarding your question, it looks like the machine where you've deployed the agent has some networking issues since it can not reach the host.

Thank you.
