### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by 1572161937** [supervisely/supervisely#663]
I have tried to `connect my computer` according to ["How to Connect Windows PC with GPU to Supervisely using WSL | Step by Step Guide | CV Tutorial"](https://www.youtube.com/watch?v=WR9qrPTn2X8). 
In `Docker Container` named `supervisely-net-client`, it always reported error: 
```
curl: (28) Failed to connect to 10.8.0.1 port 80 after 132332 ms: Couldn't connect to server
```
The `supervisely` platform reported `Network issue` as well. 
How can I fix it? Thanks for your help!

**Comment by taozhiyu** [comment]
Same, but mine was:
```
Checking connection...
ping_mtime_timeout: 180
ping_max_attempts: 3
Checking connection...
Ping failed with status: 28
Error message: curl: (28) Failed to connect to 10.8.0.1 port 80 after 10001 ms: Timeout was reached
```
( And looping... )

 <details><summary>My PC Info</summary>
<li>Planform: Windows 11 Enterprise (23H2)</li>
<li>Docker Desktop: v4.25.2</li>
<li>Docker Engine: v24.0.6</li>
</details>

**Comment by 1572161937** [comment]
这是来自QQ邮箱的自动回复邮件：您好，您的邮件我已收到，会尽快给您回复。

**Comment by iwatkot** [comment]
Hello!
We're kindly asking our users to request help and support via our Slack channel: https://supervisely.com/slack/ or e-mail: [support@supervisely.com](mailto:support@supervisely.com) since usually we'll need some more information to investigate the problem (e.g. agent logs, outputs of the commands, etc.) and we do not want to publish such data in open sources.

Thank you for understanding and sorry for the late reply.

**Comment by 1572161937** [comment]
这是来自QQ邮箱的自动回复邮件：您好，您的邮件我已收到，会尽快给您回复。
