### ISSUE TITLE
tags_images not updated according to the new .json files

### ISSUE THREAD

**Issue by ridasalam** [supervisely/supervisely#7]
Hi, i get this error with project meta.

TagMetaCollection.from_json(data[ProjectMetaJsonFields.IMG_TAGS]),
KeyError: 'tags_images'

**Comment by YaroslavSchubert** [comment]
Try with latest commit

**Comment by antonc-ds** [comment]
Hi @ridasalam. Sorry about the issue. As Yaroslav said, it has been fixed in our 20190513 release. The background is that we used to have separate sets for image tags and object tags, but that was creating a lot of complexity for multi-step pipelines. e.g. running a detector and then running a classifier over the detected bounding boxes (the tags had to be moved from image-level to object level).

So to simplify things we have merged all the tags into a single set, and any tag can be attached to either the full image or a particular object. We have gotten behind on updating the public SDK though, which is why you were getting that error. We'll try to be prompt with such updates in the future.
