### ISSUE TITLE
problem with docker

### ISSUE THREAD

**Issue by ZDOG017** [supervisely/supervisely#953]
![image](https://github.com/supervisely/supervisely/assets/58365113/5e5e7f0f-d8b3-4df9-a7f0-cc4bc87634ee)
i am using wsl on windows and ubuntu terminal can you please help I cannot create an agent and link it to my videocard.
I installed all the necessary prerequisites

**Comment by iwatkot** [comment]
@ZDOG017, hello!

Sorry, but due to the large number of repositories and limited time of our team, we're kindly asking our users, to use the following support channels:
Slack: supervisely.slack.com
E-mail: support@supervisely.com

If you still have the problem, please contact us.
Thank you
Sincerely
